### ISSUE TITLE
Scripting question

### ISSUE THREAD

**Issue by ernierasta** [Grokmoo/sulis#48]
Hi!
I am experimenting with AI. I have made some fun variations (attacking char with lowest HP, trying to kill everyone, who has less then 1/3 HP, random target), nothing special. But I was wandering, do you have recommendation how to implement mechanics, where strong hit would bring attention to striking character. This would be advantage and disadvantage to the player at the same time. You can use it to bring attention to your tank or endanger your mage by using very powerful spell. 

Not sure how to do it right, but my plan is:

- if damage is above some value (or maybe ability is used) write flag containing attacker id to the parent (enemy),
- always check for that flag and if exists and attacker is still valid, go and attack him.

Questions:
Is it possible to "catch" damage value somehow? Or ability usage? In both cases in ai script it means `target` (player) dealing damage to `parent` (enemy).
Do you have some smart way to calculate hit which makes damage bigger then average?

Btw: If You are curious (only changed part):
https://gist.github.com/ernierasta/bbc99abc8718c15bc835d50e634cb756

But You would write that in 5 minutes and probably better. ;-)

**Comment by Grokmoo** [comment]
Hey!  Jumping in and working on the AI would be great!  There is a ton of work that could be done there.

By the way, I am working on outlining the world, races, and lore right now on the website, which you had mentioned earlier.

To address your question: right now, the AI script only runs on the owner's turn, there is no way for the AI to create hooks in to be called at other times.  But, this is clearly needed for robust AI, so I will log an issue for this to get to.

A workaround to get you started on your idea (not what we would want to do long term though):

Create a dummy ability, give it to all the creatures you want to have the improved AI in the `abilities` section in the actor definition.
 
The ability looks something like this:

```
id: ai_dummy
name: "" # name being blank should prevent ability activation from showing up overhead
icon: empty
description: "AI Dummy Helper ability"
active:
  script: "ai_helper"
  group: Fighter # this needs to be an ability group the AI has access to.  You may want to create an "AI" group and put it in the standard Fighter, Rogue, Mage class defs.
  ap: 0
  duration:
    Rounds: 1000
  cooldown: 1000
  ai:
    priority: 1 #priority of 1 means the current AI script will prioritize activating it
    kind: Buff
    group: Single
    range: Personal
  short_description: ""
```
The "ai_helper.lua" script looks something like this:

```
function on_activate(parent, ability)
    effect = parent:create_effect(ability:name(), ability:duration())
    cb = ability:create_callback(parent)
    cb:set_after_defense_fn("after_defense")
    effect:add_callback(cb)
    effect:apply()
end

function after_defense(parent, ability, targets, hit)
    if hit:total_damage() < 10 then return end
    target = targets:first() # this is the attacker (should be player)
    #  save the target ID to the parent as a preferred target
end
```

Unfortunately `after_defense` will only be called on attacks or abilities that make an attack (like Mighty Blow).  But, its a start - and I can implement an `on_damaged` callback type to cover all cases.
